name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Deploy
        run: |
          python3 -m pip install -r requirements.txt
          mkdocs gh-deploy

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs/site
