name: Update Assets Data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-data:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Pip install
        run: |
          python3 -m pip install pandas

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-3
      

      - name: Update data
        env:
          BUCKET: ${{ secrets.BUCKET }}
        run: |
          YEAR=$(date '+%Y')
          DEST_DIR=docs/assets/data/sh/${YEAR}
          
          mkdir -p ${DEST_DIR}
          
          DB=${{ secrets.DATA_SOURCE }} scripts/s3cp.sh ${YEAR} /tmp/${YEAR}
          gunzip /tmp/${YEAR}/*.gz
          DEST_DIR=${DEST_DIR} scripts/stat.py /tmp/${YEAR}/*

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "./docs/assets/data/*.csv --force"
